### ISSUE TITLE
Error: establish a working "baseline" commit

### ISSUE THREAD

**Issue by danghai** [RH-FMK/sktm#66]
Hi, I got error after the command: 
```
./sktm.py -v --jjname sktm baseline \
          git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next.git \
          master
```

The output console from UI Jenkins shows the building of Kernel module and errors from: 
```
[sktm] Running shell script
+ set +x
+ skt -vv --state --rc skt-rc --junit junit run --wait
2018-06-01 13:38:51,806     INFO   runner type: beaker
2018-06-01 13:38:51,806     INFO   beaker template: beakerjob.xml
CA_CERT configuration points to non-existing file: /etc/beaker/ca.pem
2018-06-01 13:38:52,247     INFO   submitted jobid: None
2018-06-01 13:38:52,255    ERROR   Exception caught: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/skt/executable.py", line 107, in wrapper
    func(cfg)
  File "/usr/lib/python2.7/site-packages/skt/executable.py", line 289, in cmd_run
    cfg.get('wait'), uid=cfg.get('uid'))
  File "/usr/lib/python2.7/site-packages/skt/runner.py", line 455, in run
    self.wait(jobid, reschedule)
  File "/usr/lib/python2.7/site-packages/skt/runner.py", line 391, in wait
    self.add_to_watchlist(jobid, reschedule)
  File "/usr/lib/python2.7/site-packages/skt/runner.py", line 373, in add_to_watchlist
    root = self.getresultstree(jobid)
  File "/usr/lib/python2.7/site-packages/skt/runner.py", line 115, in getresultstree
    bkr = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Report)
[Pipeline] sh
[sktm] Running shell script
+ set +x
+ skt -vv --state --rc skt-rc --junit junit report --reporter mail '{'\''mailfrom'\'': '\''Jenkins <jenkins@localhost.localdomain>'\'',                           '\''mailto'\'': '\''Root <root@localhost.localdomain>'\''}'
2018-06-01 13:38:52,849    DEBUG   Starting new HTTP connection (1): pc.example.com
Traceback (most recent call last):
  File "/bin/skt", line 11, in <module>
    load_entry_point('skt==1', 'console_scripts', 'skt')()
  File "/usr/lib/python2.7/site-packages/skt/executable.py", line 871, in main
    args.func(cfg)
  File "/usr/lib/python2.7/site-packages/skt/executable.py", line 340, in cmd_report
    reporter.report()
  File "/usr/lib/python2.7/site-packages/skt/reporter.py", line 535, in report
    self.update_mergedata()
  File "/usr/lib/python2.7/site-packages/skt/reporter.py", line 264, in update_mergedata
    mergedata = self.infourldata(mergedata)
  File "/usr/lib/python2.7/site-packages/skt/reporter.py", line 217, in infourldata
    response = requests.get(self.cfg.get("infourl"))
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='pc.example.com', port=4040): Max retries exceeded with url: /result/21ad1173589ef63a93f94e05c879393e2c27588c.csv (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60efca3e50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
[Pipeline] }
[Pipeline] // stage
[Pipeline] sh
[sktm] Running shell script
+ kill 85227
[Pipeline] junit
Recording test results
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

Could you help me handle it? Thanks

**Comment by veruu** [comment]
Hi, you seem to be missing valid Beaker XML file for [skt runner](https://github.com/RH-FMK/skt#run). Without it, job for baseline can't be submitted which results in the first error. The second error says that skt is unable to resolve host `pc.example.com` . This means you probably didn't exchange the placeholders in the guide by the hostname / IP address of the machine you are using for the setup.
